### ISSUE TITLE
Add FUNDING.yml?

### ISSUE THREAD

**Issue by JohnTitor** [bastion-rs/.github#3]
Do we want to add FUNDING.yml to this repository?
If we want to display the Sponsors button on all the repositories of Bastion, we can go there.

**Comment by r3v2d0g** [comment]
I think that this makes sense to have it in this repository. Just a thought: does it show the Sponsor button on forks hosted under this organization too (thinking of bastion-rs/qutex), and if so, is there a way to deactivate that?

**Comment by JohnTitor** [comment]
> does it show the Sponsor button on forks hosted under this organization too (thinking of bastion-rs/qutex), and if so, is there a way to deactivate that?

We can manage to turn on/off in repository settings.

**Comment by r3v2d0g** [comment]
Then we should add a FUNDING.yml in this repo (bastion-rs/.github) 🙂.
